version: "2"

services:
  # web:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: web
  #   ports:
  #     - "5000:5000"

  mongodb:
    image: mongo:5.0.7
    restart: unless-stopped
    env_file: ./config/config.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=
      - MONGO_INITDB_ROOT_PASSWORD=
    ports:
      - 8080:27017
    volumes:
      - db:/data/db
  web:
    depends_on:
      - mongodb
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: web
    env_file: ./config/config.env
    ports:
      - 5000:5000
    environment:
      - DB_HOST=
      - DB_USER=
      - DB_PASSWORD=
      - DB_NAME=
    stdin_open: true
    tty: true

volumes:
  db:
